{% set name = "smact" %}
{% set version = "3.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c1c252bfffb86aef3e42f8712b0e42fbc968fe57a792d22c87cfe61e42761e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - numpy<3
    - spglib>=2.6.0
    - pymatgen>=2024.2.20
    - ase
    - pandas
    - pathos
    - pandarallel[optional]>=1.6.5"
    - typing-extensions


test:
  imports:
    - smact
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WMD-group/SMACT
  summary: Python package to aid materials design and informatics
  description: |
    Semiconducting Materials by Analogy and Chemical Theory (SMACT)
    is a collection of rapid screening tools that uses data about chemical elements.
  license: MIT
  license_file: LICENSE
  doc_url: https://smact.readthedocs.io/en/latest/
  dev_url: https://github.com/WMD-group/SMACT

extra:
  recipe-maintainers:
    - AntObi
