{% set name = "smact" %}
{% set version = "3.0.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34b73147a242b8f2ec23dd8a588ac05f3ab14fb3949b2502c47a9ba3c9607e5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - numpy
    - spglib
    - pymatgen
    - ase
    - pandas
    - pathos

test:
  imports:
    - smact
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WMD-group/SMACT
  summary: Python package to aid materials design and informatics
  description: |
    Semiconducting Materials by Analogy and Chemical Theory (SMACT)
    is a collection of rapid screening tools that uses data about chemical elements.
  license: MIT
  license_file: LICENSE
  doc_url: https://smact.readthedocs.io/en/latest/
  dev_url: https://github.com/WMD-group/SMACT

extra:
  recipe-maintainers:
    - AntObi
