{% set name = "smact" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 763d1b4e8d8ba490e21a5a5989d107e475608c418e388722ba0359a22b50c15f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - scipy
    - numpy
    - spglib
    - pymatgen
    - ase
    - pandas
    - pathos

test:
  imports:
    - smact
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WMD-group/SMACT
  summary: Python package to aid materials design and informatics
  description: |
    Semiconducting Materials by Analogy and Chemical Theory (SMACT)
    is a collection of rapid screening tools that uses data about chemical elements.
  license: MIT
  license_file: LICENSE
  doc_url: https://smact.readthedocs.io/en/latest/
  dev_url: https://github.com/WMD-group/SMACT

extra:
  recipe-maintainers:
    - AntObi
